spring:
  application:
    name: invest-mate-ai

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/invest_ai_local
    username: invest_ai
    password: Investai12!@

mybatis:
  ## mapper 파일 경로
  mapper-locations: classpath:/mapper/**/*.xml
  ## vo 파일 경로
  type-aliases-package: com.example.invest_mate_ai
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %-5level %logger{36} - %msg%n"
  level:
    com.example.invest_mate_ai: DEBUG

google:
  oauth:
#    client-id: 657975510865-5cpads4vve566999brrublhev328ujqt.apps.googleusercontent.com
#    client-secret: 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
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/auth/oauth2/google/callback
    google-auth-uri: https://accounts.google.com/o/oauth2/v2/auth
    token-api-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://oauth2.googleapis.com/tokeninfo